Create README.md for organization overview.
Imageomics/.github pull request #1
Opened 2023-04-05 15:24 UTC by thompsonmj

2023-04-05 16:31 UTC, hlapp commented
As I said, we shouldn't have divergent definitions of Imageomics in different places, so the one here (which I don't think has been discussed or approved by the leadership team?) needs to be changed.

2023-04-05 17:08 UTC, hlapp commented
> As I said, we shouldn't have divergent definitions of Imageomics in different places, so the one here (which I don't think has been discussed or approved by the leadership team?) needs to be changed.

Fixed.

2023-04-05 17:39 UTC, hlapp commented
* [ ] @balhoff could you please check the list for Phenoscape and add repositories you think would also specifically fall into the Imageomics context? (Phenex perhaps?)
* [ ] @johnbradley could you add the BGNN repos specifically involved in the Minnow Traits project & manuscript?
* [ ] @thompsonmj can you coordinate with @smrolfe and @muratmaga which repos from their GitHub presence should be linked here? (Perhaps SlicerMorph? ml-morph?)
* [ ] @susan1637 and/or @xbahadirx, could you add (or list in a comment) repos to add here from the TUBRI Github organization?

2023-04-05 18:31 UTC, balhoff requested changes
Added Phenex link as suggested by @hlapp.

2023-04-05 18:31 UTC, balhoff commented on profile/README.md
> +    * ...
```suggestion
    * [Phenex](https://github.com/phenoscape/Phenex)
```

2023-04-10 20:32 UTC, thompsonmj commented
Added products from Murat, Sara, and Arthur.

2023-04-10 22:16 UTC, hlapp commented
@susan1637 @xbahadirx @uyedaj last call. We'll wrap this up Thursday at the latest.

2023-04-13 21:50 UTC, hlapp commented
@balhoff I don't know whether you previously submitted a formal review requesting changes, but somehow it doesn't recognize the resolved comment as having resolved the requested change. When you get a chance, can you submit an approval?

2023-04-13 21:53 UTC, hlapp commented
> @balhoff I don't know whether you previously submitted a formal review requesting changes, but somehow it doesn't recognize the resolved comment as having resolved the requested change. When you get a chance, can you submit an approval?

Scratch that. I just found a way to dismiss your earlier review (even if in actuality I didn't dismiss it 🧐)

2023-04-13 22:01 UTC, hlapp commented
@cvstewart @dboghrat @tanyabw once merged, this will appear as part of our [Github organization profile](https://github.com/imageomics). In addition to the version control diff, you can also [see the file in HTML rendering](https://github.com/Imageomics/.github/blob/037a49672b138137b247c9f3046053b332aeb7e7/profile/README.md) (which is how it would appear).

My main ask here is to check whether the content is all OK to go live, or whether (and which) further corrections need to be made. (You can see in the thread here who contributed.)

My hunch is that it is too much information to fit well on the organization profile, and that we'll probably want to move some of this to a different place, such as the website. But we can deal with bite-sizing it more in a subsequent step.

2023-05-05 16:38 UTC, dboghrat approved these changes

2023-05-05 16:41 UTC, merged